### PR TITLE
WIP: Setup/bitrise snapshot ios

### PR DESCRIPTION
**Pull request by zirconias**
see #4 

- [x] updating bitrise

- [x] updating fastlane / snapshot

- [x] simple UI test

- [x] bitrise workflow

todo: 

- [ ] change bitrise.yml, add rest of the workflow, and test it in bitrise.io

### CODE REVIEW

**Comment by vidbina** [comment]
Workflow is set to the bitrise.yml in 8585e98

Still getting

```
[21:53:05]: ▸ Loading...
[21:53:12]: ▸ Building RCTGeolocation/RCTGeolocation [Debug]
[21:53:12]: ▸ Check Dependencies
[21:53:12]: ▸ ❌  /Users/vagrant/git/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: 'React/RCTEventEmitter.h' file not found
[21:53:12]: ▸ #import <React/RCTEventEmitter.h>
[21:53:12]: ▸         ^
[21:53:18]: ▸ ❌  /Users/vagrant/git/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: 'React/RCTEventEmitter.h' file not found
[21:53:18]: ▸ #import <React/RCTEventEmitter.h>
[21:53:18]: ▸         ^
[21:53:18]: ▸ ** BUILD FAILED **
[21:53:18]: ▸ The following commands produced analyzer issues:
[21:53:18]: ▸ Analyze RCTLocationObserver.m
[21:53:18]: ▸ (1 command with analyzer issues)
[21:53:18]: ▸ The following build commands failed:
[21:53:18]: ▸ Analyze RCTLocationObserver.m
[21:53:18]: ▸ CompileC /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/snapshot_derived20170420-2310-1yomlw8/Build/Intermediates/RCTGeolocation.build/Debug-iphonesimulator/RCTGeolocation.build/Objects-normal/x86_64/RCTLocationObserver.o RCTLocationObserver.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[21:53:18]: ▸ (2 failures)
[21:53:18]: ▸ 2017-04-20 21:53:18.434 xcodebuild[2493:13940]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[21:53:18]: ▸ /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/snapshot_derived20170420-2310-1yomlw8/Logs/Test/33FB099B-E088-4DEA-AAC0-0E41043E8DCE/Session-WinAdmCockpitUITests-2017-04-20_215318-07Jbfa.log
[21:53:18]: ▸ 2017-04-20 21:53:18.434 xcodebuild[2493:13458] [MT] IDETestOperationsObserverDebug: (AA195D0E-8E3F-4A9D-BA70-5812DDD0C79B) Beginning test session WinAdmCockpitUITests-AA195D0E-8E3F-4A9D-BA70-5812DDD0C79B at 2017-04-20 21:53:18.428 with Xcode 8E1000a on target <DVTiPhoneSimulator: 0x7fcdddaf8590> {
[21:53:18]: ▸ SimDevice: SimDevice : iPhone 6 (7E73D7E0-E63F-42DB-82CC-4E55B311516D) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 9.3 (13E233) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
[21:53:18]: ▸ } (9.3 (13E233))
[21:53:18]: ▸ Building RCTGeolocation/RCTGeolocation [Debug]
[21:53:18]: ▸ Check Dependencies
[21:53:18]: ▸ ❌  /Users/vagrant/git/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: 'React/RCTEventEmitter.h' file not found
[21:53:18]: ▸ #import <React/RCTEventEmitter.h>
[21:53:18]: ▸         ^
[21:53:18]: ▸ ❌  /Users/vagrant/git/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: 'React/RCTEventEmitter.h' file not found
[21:53:18]: ▸ #import <React/RCTEventEmitter.h>
[21:53:18]: ▸         ^
[21:53:18]: ▸ 2017-04-20 21:53:18.919 xcodebuild[2493:13458] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/snapshot_derived20170420-2310-1yomlw8/Logs/Test/33FB099B-E088-4DEA-AAC0-0E41043E8DCE/Session-WinAdmCockpitUITests-2017-04-20_215318-07Jbfa.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/snapshot_derived20170420-2310-1yomlw8/Logs/Test/33FB099B-E088-4DEA-AAC0-0E41043E8DCE/Session-WinAdmCockpitUITests-2017-04-20_215318-07Jbfa.log}
[21:53:18]: ▸ 2017-04-20 21:53:18.921 xcodebuild[2493:13980] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fcdde30d940>
[21:53:18]: ▸ Testing failed:
[21:53:18]: ▸ Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
[21:53:18]: ▸ 'React/RCTEventEmitter.h' file not found
[21:53:18]: ▸ ** TEST FAILED **
[21:53:18]: ▸ The following commands produced analyzer issues:
[21:53:18]: ▸ Analyze RCTLocationObserver.m
[21:53:18]: ▸ (1 command with analyzer issues)
[21:53:18]: ▸ The following build commands failed:
[21:53:18]: ▸ Analyze RCTLocationObserver.m
[21:53:18]: ▸ (1 failure)
```

How about trying to manage the Xcode framework dependencies through cocoapods
 - http://blog.bitrise.io/2016/05/20/cocoapods-1-0.html
 - https://facebook.github.io/react-native/docs/integration-with-existing-apps.html
as I believe this issue may be an Xcode problem.

If I recall correctly some npm packages would require the execution of a `rnpm link` (see https://github.com/andpor/react-native-sqlite-storage for an example) command in order to take care of setting up the related Frameworks in Xcode. So installation of the npm packages through yarn will most likely not be sufficient. The reason this project may still build on our boxes may have something to do with us having linked all these Frameworks into Xcode in the past but I'm just talking 💩  since I'm not at all confident that Xcode maintains some sense of state of installed Frameworks over time. I would've hoped that everything necessary would be encoded into the .xcodeproj or other contained files but the evidence on the CI env seems to suggest otherwise. My first guess from the output observed on the CI env is that the missing elements supposedly should be part of the react-native framework itself which I suppose is not linked in Xcode in that environment.

Since the react-native documentation seems to prefer the cocoapods route, I'd recommend we go for that :wink:

**Review by vidbina — CHANGES_REQUESTED** [review]
I just setup the Workflow on bitrise to be in sync with the bitrise.yml in the last commit, I made. I've opened up a new issue to pull in the bitrise.yml on every build which I will tackle since it requires some configuration on bitrise.io itself. For now we have to deal with some sense of state the Xcode seems to maintain in our local dev envs with regards to Frameworks. Apparently they are not linked on the CI env. I believe Cocoapods could be used to handle that issue. See my prior comments :wink:

**Comment by vidbina** [comment]
@zirconias I just triggered a [build on your last commit with the Workflow similar to the bitrise.yml file in my commit](https://www.bitrise.io/build/2a71f38156429c28) :wink: just to allow you to see how the ci env fails to complete the build.

**Comment by zirconias** [comment]
indeed, one step we need to do is `react-native link` , i guessed that when once i do it. it adds all thoses deps to .xcodeproj.
can we add this step just to test if it passes? 
i'll see cocoa lead.
why when i first commited screenshot passes :s 
https://www.bitrise.io/build/09aa6bfffa2bed8d

**Review by vidbina — CHANGES_REQUESTED** [review]
I notice ios/WinAdmCockpitUITests/TestLogin.swift and ios/WinAdmCockpitUITests/testLogin.swift, I believe testLogin.swift doesn't really do anything. Perhaps we should clean up the test directory. Probably something I'll take care off.

Also, in case we redo the setup of this project, we should make sure that the project name is just variable.

**Comment by zirconias** [comment]
indeed tried to clean up the project,
but bit by bit, i was afraid of breaking things with xcodeproj.

**Comment by zirconias** [comment]
and i think it's already done by xcode,  it's all about variables
${PRODUCT_NAME} for bundle name, so we need to figure out how to pass value to those variables.

**Pull request merged**
