### PR TITLE
Upgrade/react native for android

### PR DESCRIPTION
**Pull request by vidbina**

### CODE REVIEW

**Comment by zirconias** [comment]
nice work buddy +1 ,  i'll pull and see what it gives :p

**Comment by vidbina** [comment]
sure, let me know. I'm cleaning up a bit and setting up some tools to simplify the build process before starting other app projects :wink:

**Comment by zirconias** [comment]
react-native is on v .43 , we should update libs.

**Comment by vidbina** [comment]
Assigned #5 to address this. You will find the branch to commit changes to in the issue.

**Pull request merged**
