### PR TITLE
Setup & upgrade deps

### PR DESCRIPTION
**Pull request by zirconias**
- [x] update to .40

- [x] updates other dependencies

- [x] test in android simulator

### CODE REVIEW

**Comment by vidbina** [comment]
@zirconias, Were you unable to test your changes on the iOS sim? You only mention testing in Android.

**Comment by zirconias** [comment]
references #5 . 
it works on both ios and android sim now.

**Review by vidbina — COMMENTED** [review]
I noticed we don't have the latest versions of some dependencies, but since every project will have to go through a depedency upgrade #5 multiple times through it's lifetime, we will be able to tackle this again at a later stage :wink:. Let's move forward on #7

**Comment by vidbina** [comment]
closes #5, for now. For #13, I may have to reboot issue #5, but let's tackle one thing at a time. We're going to have to reboot it multiple tmes anyways throughout the lifecycle of the project.

**Comment by zirconias** [comment]
yes,  there is one or 2 version to upgrade,  
dependencies are broken when updating some libs. so we need to keep them.

also  rn v.43 uses the latest react which is in alpha stage for now.

**Pull request merged**
